#pragma once

extern "C" {
#include "../build/immediate/y.tab.h"
}

#include <map>
#include <string>
#include <string_view>

using namespace std::string_literals;

const std::map<int, std::string_view> tokenNames = {
	{ IDENTIFIER			, "IDENTIFIER"sv },
	{ I_CONSTANT			, "I_CONSTANT"sv },
	{ F_CONSTANT			, "F_CONSTANT"sv },
	{ STRING_LITERAL		, "STRING_LITERAL"sv },
	{ FUNC_NAME				, "FUNC_NAME"sv },
	{ SIZEOF				, "SIZEOF"sv },
	{ PTR_OP				, "PTR_OP"sv },
	{ INC_OP				, "INC_OP"sv },
	{ DEC_OP				, "DEC_OP"sv },
	{ LEFT_OP				, "LEFT_OP"sv },
	{ RIGHT_OP				, "RIGHT_OP"sv },
	{ LE_OP					, "LE_OP"sv },
	{ GE_OP					, "GE_OP"sv },
	{ EQ_OP					, "EQ_OP"sv },
	{ NE_OP					, "NE_OP"sv },
	{ AND_OP				, "AND_OP"sv },
	{ OR_OP					, "OR_OP"sv },
	{ MUL_ASSIGN			, "MUL_ASSIGN"sv },
	{ DIV_ASSIGN			, "DIV_ASSIGN"sv },
	{ MOD_ASSIGN			, "MOD_ASSIGN"sv },
	{ ADD_ASSIGN			, "ADD_ASSIGN"sv },
	{ SUB_ASSIGN			, "SUB_ASSIGN"sv },
	{ LEFT_ASSIGN			, "LEFT_ASSIGN"sv },
	{ RIGHT_ASSIGN			, "RIGHT_ASSIGN"sv },
	{ AND_ASSIGN			, "AND_ASSIGN"sv },
	{ XOR_ASSIGN			, "XOR_ASSIGN"sv },
	{ OR_ASSIGN				, "OR_ASSIGN"sv },
	{ TYPEDEF_NAME			, "TYPEDEF_NAME"sv },
	{ ENUMERATION_CONSTANT	, "ENUMERATION_CONSTANT"sv },
	{ TYPEDEF				, "TYPEDEF"sv },
	{ EXTERN				, "EXTERN"sv },
	{ STATIC				, "STATIC"sv },
	{ AUTO					, "AUTO"sv },
	{ REGISTER				, "REGISTER"sv },
	{ INLINE				, "INLINE"sv },
	{ CONST					, "CONST"sv },
	{ RESTRICT				, "RESTRICT"sv },
	{ VOLATILE				, "VOLATILE"sv },
	{ BOOL					, "BOOL"sv },
	{ CHAR					, "CHAR"sv },
	{ SHORT					, "SHORT"sv },
	{ INT					, "INT"sv },
	{ LONG					, "LONG"sv },
	{ SIGNED				, "SIGNED"sv },
	{ UNSIGNED				, "UNSIGNED"sv },
	{ FLOAT					, "FLOAT"sv },
	{ DOUBLE				, "DOUBLE"sv },
	{ VOID					, "VOID"sv },
	{ COMPLEX				, "COMPLEX"sv },
	{ IMAGINARY				, "IMAGINARY"sv },
	{ STRUCT				, "STRUCT"sv },
	{ UNION					, "UNION"sv },
	{ ENUM					, "ENUM"sv },
	{ ELLIPSIS				, "ELLIPSIS"sv },
	{ CASE					, "CASE"sv },
	{ DEFAULT				, "DEFAULT"sv },
	{ IF					, "IF"sv },
	{ ELSE					, "ELSE"sv },
	{ SWITCH				, "SWITCH"sv },
	{ WHILE					, "WHILE"sv },
	{ DO					, "DO"sv },
	{ FOR					, "FOR"sv },
	{ GOTO					, "GOTO"sv },
	{ CONTINUE				, "CONTINUE"sv },
	{ BREAK					, "BREAK"sv },
	{ RETURN				, "RETURN"sv },
	{ ALIGNAS				, "ALIGNAS"sv },
	{ ALIGNOF				, "ALIGNOF"sv },
	{ ATOMIC				, "ATOMIC"sv },
	{ GENERIC				, "GENERIC"sv },
	{ NORETURN				, "NORETURN"sv },
	{ STATIC_ASSERT			, "STATIC_ASSERT"sv },
	{ THREAD_LOCAL			, "THREAD_LOCAL"sv },
};